export const data = [
    {
       title: "NATURE",
       "body": "body",
       pictures: ['/images/minors/nature25.jpg', '/images/minors/nature17.avif', '/images/minors/nature23.jpg', '/images/minors/nature18.jpg', '/images/minors/nature5.jpg', '/images/minors/nature26.jpg', '/images/minors/nature6.jpg', '/images/minors/nature19.jpg',  '/images/minors/nature10.avif', '/images/minors/nature21.jpg', '/images/minors/nature8.avif', '/images/minors/nature2.jpg', '/images/minors/nature24.jpg', '/images/minors/nature13.jpg', '/images/minors/nature16.avif', '/images/minors/nature15.jpg', '/images/minors/nature12.jpg', '/images/minors/nature1.jpg', '/images/minors/nature14.jpg', '/images/minors/nature7.avif', '/images/minors/nature9.avif', '/images/minors/nature22.jpg', '/images/minors/nature4.jpg', '/images/minors/nature3.jpg', '/images/minors/nature11.jpg'],
       mainpic: "/images/mainpics/nature.avif",
       caption: "Natural And Wonderful Pictures",
       headline: "pictures",
       id: 0
     },

     {
      title: "ART",
      "body": "body",
       pictures: ['/images/minors/art25.jpg', '/images/minors/art2.jpg', '/images/minors/art11.jpg','/images/minors/art19.jpg',  '/images/minors/art12.avif', '/images/minors/art21.jpg', '/images/minors/art11.jpg', '/images/minors/art22.jpg', '/images/minors/art13.jpg', '/images/minors/art23.jpg','/images/minors/art20.jpg', '/images/minors/art9.jpg', '/images/minors/art16.avif', '/images/minors/art27.avif', '/images/minors/art14.jpg', '/images/minors/art10.avif', '/images/minors/art3.jpg', '/images/minors/art17.jpg', '/images/minors/art6.jpg', '/images/minors/art7.jpg', '/images/minors/art26.jpg', '/images/minors/art1.jpg', '/images/minors/art4.jpg', '/images/minors/art15.jpg', '/images/minors/art24.jpg', '/images/minors/art18.jpg'],
              // mainpic: "/images/mainpics/img1.jpg",
      mainpic: "/images/mainpics/art.avif",
      caption: "Beautiful Paintings, And Statues",
      headline: "pictures",
      id: 1
     },

     
     {
      title: "WEDDINGS",
      "body": "body",
      pictures: [
        "/images/minors/wed2.jpg",
        "/images/minors/wed1.jpg",
        "/images/minors/wed3.jpg",
        "/images/minors/wed4.jpg",
        "/images/minors/wed5.jpg",
        "/images/minors/wed6.jpg",
        "/images/minors/wed7.jpg",
        "/images/minors/wed8.jpg",
        "/images/minors/wed9.jpg",
        "/images/minors/wed10.jpg",
        "/images/minors/wed11.jpg",
        "/images/minors/wed12.jpg",
        "/images/minors/wed13.jpg",
        "/images/minors/wed14.jpg",
        "/images/minors/wed15.jpg",
        "/images/minors/wed16.jpg",
        "/images/minors/wed17.jpg",
        "/images/minors/wed18.jpg",
        "/images/minors/wed19.jpg",
        "/images/minors/wed20.jpg",
        "/images/minors/wed21.jpg",
        "/images/minors/wed22.jpg",
        "/images/minors/wed23.jpg",
        "/images/minors/wed24.jpg",
        "/images/minors/wed25.jpg",
        "/images/minors/wed26.jpg",
      ],
      mainpic: "/images/mainpics/weddings.avif",
      caption: "Beautiful Weddings, And Engagements Photos",
      headline: "pictures",
      id: 2
    },

    
    {
      title: "PARTIES",
      "body": "body",
      pictures: [
        "/images/minors/party2.jpg",
        "/images/minors/party3.jpg",
        "/images/minors/party4.jpg",
        "/images/minors/party5.jpg",
        "/images/minors/party6.jpg",
        "/images/minors/party7.jpg",
        "/images/minors/party8.jpg",
        "/images/minors/party9.jpg",
        "/images/minors/party10.jpg",
        "/images/minors/party11.jpg",
        "/images/minors/party12.jpg",
        "/images/minors/party13.jpg",
        "/images/minors/party14.jpg",
        "/images/minors/party15.jpg",
        "/images/minors/party16.jpg",
        "/images/minors/party17.jpg",
        "/images/minors/party18.jpg",
        "/images/minors/party19.jpg",
        "/images/minors/party20.jpg",
        "/images/minors/party21.jpg",
        "/images/minors/party22.jpg",
        "/images/minors/party23.jpg",
        "/images/minors/party24.jpg",
        "/images/minors/party25.jpg",
        "/images/minors/party26.jpg",
      ],
      mainpic: "/images/mainpics/parties.avif",
      caption: "Classic Memorable Nights, And Dancing",
      headline: "pictures",
      id: 3
    },
    {
      title: "FAMILY",
      "body": "body",
      pictures: [
        "/images/minors/family4.jpg",
        "/images/minors/family1.jpg",
        "/images/minors/family2.jpg",
        "/images/minors/family3.jpg",
        "/images/minors/family5.jpg",
        "/images/minors/family6.jpg",
        "/images/minors/family7.jpg",
        "/images/minors/family8.jpg",
        "/images/minors/family9.jpg",
        "/images/minors/family10.jpg",
        "/images/minors/family11.jpg",
        "/images/minors/family12.jpg",
        "/images/minors/family13.jpg",
        "/images/minors/family14.jpg",
        "/images/minors/family15.jpg",
        "/images/minors/family16.jpg",
        "/images/minors/family17.jpg",
        "/images/minors/family18.jpg",
        "/images/minors/family19.jpg",
        "/images/minors/family20.jpg",
        "/images/minors/family21.jpg",
        "/images/minors/family22.jpg",
        "/images/minors/family23.jpg",
        "/images/minors/family24.jpg",
        "/images/minors/family25.jpg",
      ],
      mainpic: "/images/mainpics/family.avif",
      caption: "Gorgeous Family Sessions",
      id: 4
    },

    {
      title: "SPORT",
      "body": "body",
      pictures: ["/images/minors/sport21.jpg", "/images/minors/sport20.jpg", "/images/minors/sport19.jpg", "/images/minors/sport18.jpg","/images/minors/sport8.jpg", "/images/minors/sport17.jpg", "/images/minors/sport16.jpg", "/images/minors/sport15.jpg", "/images/minors/sport14.jpg", "/images/minors/sport13.jpg", "/images/minors/sport12.jpg", "/images/minors/sport11.jpg", "/images/minors/sport10.jpg", "/images/minors/sport9.jpg",  "/images/minors/sport7.jpg", "/images/minors/sport6.jpg", "/images/minors/sport5.jpg", "/images/minors/sport4.jpg", "/images/minors/sport3.jpg", "/images/minors/sport2.jpg", "/images/minors/sport1.jpg"],
      mainpic: "/images/mainpics/sports.avif",
      caption: "Sports And Athletic Competitions",
      id: 5
    }
    
   ];